---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  -
    repo: https://github.com/aws-ia/pre-commit-configs
    # To update run:
    # pre-commit autoupdate --freeze
    rev: c7091ec774495a41986bd9c5ea59152655ec4f3a  # frozen: v1.6.2
    hooks:
      - id: aws-ia-meta-hook
